version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "15:00"
      timezone: "UTC"
    target-branch: "develop"
    # Only allow security updates - blocks regular dependency updates
    # See https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference?search-overlay-input=which+metadata+would+apply+to+composer-based+security+updates&search-overlay-ask-ai=true#open-pull-requests-limit-
    open-pull-requests-limit: 0
    # Add labels to identify security PRs
    labels:
      - "security"
      - "dependencies"
    # Optional: Customize commit messages for security updates
    commit-message:
      prefix: "security"
      prefix-development: "security"
      include: "scope"
