version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "20:00"
      timezone: "UTC"
    target-branch: "develop"
    open-pull-requests-limit: 10
    labels:
      - "security"
      - "dependencies"
    commit-message:
      prefix: "security"
      prefix-development: "security"
      include: "scope"
    allow:
      - dependency-type: "production"
