# Legacy node_modules behavior.
nodeLinker: node-modules

# Disable lifecycle scripts to mitigate supply chain attacks.
enableScripts: false

# Disable git repositories as package sources to mitigate supply chain attacks.
approvedGitRepositories: [ ]
