#!/bin/bash

## Description: Converts a PDF file to HTML
## Usage: pdftohtml <pdf-file> <html-dir>
## Example: "ddev pdftohtml my.pdf mydir"

if [ "$#" -ne 2 ]; then
  echo "Usage: pdftohtml <pdf-file> <html-dir>"
  exit 1
fi

pdftohtml -overwrite pdfs/"$1" pdfs/"$2"
