#!/bin/bash

## Description: Run cspell on a specific module.
## Usage: cspell MODULE_NAME
## Example: "ddev cspell admin_toolbar"

if [ $# -eq 0 ]
then
  echo "You must specify a module; e.g. 'ddev check admin_toolbar'"
  exit
fi

if [ ! -d "web/modules/contrib/$1" ]
then
  echo "The specified module [$1] does not exist in /web/modules/contrib."
  exit
fi

cp /var/www/html/web/core/misc/cspell/drupal-dictionary.txt /var/www/html/web/core/misc/cspell/drupal-dictionary-bak.txt

# Append / replace core file web/core/misc/cspell/drupal-dictionary.txt
if [ -f "web/modules/contrib/$1/.cspell-project-words.txt" ]
then
  echo "Copying cspell file"
  paste -d "\n" /var/www/html/web/core/misc/cspell/drupal-dictionary.txt /var/www/html/web/modules/contrib/$1/.cspell-project-words.txt > /var/www/html/web/core/misc/cspell/drupal-dictionary-2.txt
  cp /var/www/html/web/core/misc/cspell/drupal-dictionary-2.txt /var/www/html/web/core/misc/cspell/drupal-dictionary.txt
fi

cd /var/www/html/web/core

npx cspell --show-suggestions --show-context --no-progress "../modules/contrib/$1/**"

mv /var/www/html/web/core/misc/cspell/drupal-dictionary-bak.txt /var/www/html/web/core/misc/cspell/drupal-dictionary.txt
