#!/bin/bash

## Description: Performs a default drupal installation
## Usage: install
## Example: "ddev install"

drush site:install standard --account-name=admin --account-pass=admin --site-name="Drupal 10" -y
drush en admin_toolbar admin_toolbar_tools config_inspector devel

# Install eslint dependencies
# The "--cwd" argument doesn't work with Yarn 4.4, because the global version
# is returned as 1.22.22 when Yarn starts, before switching directories.
cd $DDEV_DOCROOT/core
yarn install
cd -
# Configure prettier
test -e .prettierrc.json || ln -s $DDEV_DOCROOT/core/.prettierrc.json .
test -e .prettierignore || echo '*.yml' > .prettierignore
