#!/bin/bash

## Description: Run php code sniffer on a specific module.
## Usage: sniff MODULE_NAME
## Example: "ddev snigg admin_toolbar"

if [ $# -eq 0 ]
then
  echo "You must specify a module; e.g. 'ddev sniff admin_toolbar'"
  exit
fi

if [ ! -d "web/modules/contrib/$1" ]
then
  echo "The specified module [$1] does not exist in /web/modules/contrib."
  exit
fi

echo "======================"
echo "Running code sniffer against: /web/modules/contrib/$1"
echo "======================"

# auto-fix what can be fixed
echo "--------------"
echo "Running PHPCBF"
echo "--------------"
vendor/bin/phpcbf web/modules/contrib/$1 --standard="Drupal,DrupalPractice" -n --extensions="php,module,inc,install,test,profile,theme"
# find what is left to fix
echo "-------------"
echo "Running PHPCS"
echo "-------------"
vendor/bin/phpcs web/modules/contrib/$1 --standard="Drupal,DrupalPractice" -n --extensions="php,module,inc,install,test,profile,theme"
echo "----------------------------------------------------"
echo "Running PHPCS with PHP Compatibility coding standard"
echo "----------------------------------------------------"
vendor/bin/phpcs -p web/modules/contrib/$1 --standard="PHPCompatibility" --runtime-set testVersion "8.1" --extensions="php,module,inc,install,test,profile,theme"
