#!/bin/bash

## Description: Run tests on a specific module.
## Usage: test MODULE_NAME {TEST_TYPE} {TEST CLASS}
## Example: "ddev test admin_toolbar"
## Example: "ddev test admin_toolbar AdminToolbarAdminMenuTest"

if [ $# -eq 0 ]
then
  echo "You must specify a module; e.g. 'ddev test admin_toolbar'"
  exit
fi

if [ ! -d "web/modules/contrib/$1" ]
then
  echo "The specified module [$1] does not exist in /web/modules/contrib."
  exit
fi

# Ensure we have a files directory for test output.
if [ ! -d "web/sites/simpletest/browser_output" ]
then
  # See https://linuxize.com/post/bash-wait/
  if [ ! -d "web/sites/simpletest" ]
  then
    mkdir web/sites/simpletest &
    PROCESS_ID=$!
    wait $PROCESS_ID
  fi
  mkdir web/sites/simpletest/browser_output
  echo "Created an output directory"
fi

CONFIG='/var/www/html/phpunit.xml'
TEST_FILE=`find -type f -name $2.php`

if [ ! -z $2 ] && [ ! -z $TEST_FILE ]
then
  echo "============="
  echo "Running test: $TEST_FILE"
  echo "============="
  vendor/bin/phpunit -c "$CONFIG" --testdox "$TEST_FILE"
else
  echo "======================"
  echo "Running tests against: /web/modules/contrib/$1"
  echo "======================"
  vendor/bin/phpunit -c "$CONFIG" --testdox "web/modules/contrib/$1"
fi

echo "-- When you are finished, run 'ddev cleanup' to remove test files."
