name: workflow.yml
run-name: ${{ github.actor }} test
on: [push]
jobs:
  check-available-updates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check updates
        id: updates
        uses: valicm/drupal-update@v4
