name: Composer Audit
on: [push]
jobs:
  composer-audit:
    runs-on: ubuntu-latest
    name: Composer audit
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
        with:
          path: 'github/workspace'
          set-safe-directory: '/github/workspace'

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@2.35.4
        with:
          coverage: "none"
          php-version: 8.2
          tools: composer:v2

      - name: "Composer install"
        uses: "ramsey/composer-install@2.2.0"
        with:
          composer-options: "--prefer-dist"

      - name: Run composer audit
        uses: alamirault/composer-audit-action@v1
