name: D10 Composer Audit Test
on: push
jobs:
  drupal-security-audit:
    runs-on: ubuntu-latest
    name: Drupal security audit
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@2.35.4
        with:
          coverage: "none"
          php-version: 8.2
          tools: composer:v2

      - name: "Composer install"
        uses: "ramsey/composer-install@2.2.0"
        with:
          composer-options: "--prefer-dist"

      - name: Run composer audit for Drupal packages
        run: |
          echo "# Drupal Security Audit Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          # Run audit in table format
          composer audit --locked --format=table > audit_table.txt 2>&1 || AUDIT_EXIT_CODE=$?

          # Check if Drupal packages have vulnerabilities
          if [ -f "audit_table.txt" ] && grep -q "drupal/" audit_table.txt; then
            echo "⚠️ **Security vulnerabilities detected in Drupal packages!**" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
            tail -n +2 audit_table.txt >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY

            echo "❌ Drupal security audit failed - vulnerabilities found in Drupal packages"
            echo "Security vulnerabilities found:"
            tail -n +2 audit_table.txt
            exit 1
          else
            echo "✅ **No security vulnerabilities found in Drupal packages!**" >> $GITHUB_STEP_SUMMARY
            
            if [ "${AUDIT_EXIT_CODE:-0}" != "0" ]; then
              echo "" >> $GITHUB_STEP_SUMMARY
              echo "ℹ️ **Note:** Security issues were found in non-Drupal packages, but no Drupal packages are affected." >> $GITHUB_STEP_SUMMARY
            else
              echo "" >> $GITHUB_STEP_SUMMARY
              echo "✅ **No security issues found in any packages (including non-Drupal packages)!**" >> $GITHUB_STEP_SUMMARY
            fi
            
            echo "✅ Drupal security audit passed - no vulnerabilities detected in Drupal packages"
          fi
