name: D10 Composer Audit Test
on:
  schedule:
      - cron: '0 20 * * *' # Runs every day at 8PM UTC
jobs:
  composer-audit:
    runs-on: ubuntu-latest
    name: Composer audit
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@2.35.4
        with:
          coverage: "none"
          php-version: 8.2
          tools: composer:v2

      - name: "Composer install"
        uses: "ramsey/composer-install@2.2.0"
        with:
          composer-options: "--prefer-dist"

      - name: Run composer audit
        run: |
          echo "# Composer Security Audit Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          # Run audit and capture output
          if composer audit --format=table > audit_output.txt 2>&1; then
            echo "✅ **No security vulnerabilities found!**" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
            cat audit_output.txt >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
            echo "✅ Composer audit passed - no vulnerabilities detected"
          else
            echo "⚠️ **Security vulnerabilities detected!**" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
            cat audit_output.txt >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
            echo "❌ Composer audit failed - vulnerabilities found"
            cat audit_output.txt
            exit 1
          fi
