name: D10 Composer Audit Test
on: push
jobs:
  drupal-security-audit:
    runs-on: ubuntu-latest
    name: Drupal security audit
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@2.35.4
        with:
          coverage: "none"
          php-version: 8.2
          tools: composer:v2

      - name: "Composer install"
        uses: "ramsey/composer-install@2.2.0"
        with:
          composer-options: "--prefer-dist"

      - name: Run composer audit for Drupal packages
        run: |
          echo "# Drupal Security Audit Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          # Run audit in table format
          composer audit --locked --format=table > audit_table.txt 2>&1 || AUDIT_EXIT_CODE=$?

          # Check if we have any vulnerabilities at all
          if [ -f "audit_table.txt" ] && [ "${AUDIT_EXIT_CODE:-0}" != "0" ]; then
            # Separate Drupal and non-Drupal vulnerabilities
            HAS_DRUPAL=$(grep -q "drupal/" audit_table.txt && echo "true" || echo "false")
            # Check for non-Drupal packages (packages that are not drupal/)
            HAS_NON_DRUPAL=$(grep "^| Package" audit_table.txt | grep -v "drupal/" | grep -q "|" && echo "true" || echo "false")
            
            # Show Drupal vulnerabilities if any
            if [ "$HAS_DRUPAL" = "true" ]; then
              echo "⚠️ **Security vulnerabilities detected in Drupal packages!**" >> $GITHUB_STEP_SUMMARY
              echo "" >> $GITHUB_STEP_SUMMARY
              echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
              # Show complete table but filter for readability in summary
              tail -n +2 audit_table.txt >> $GITHUB_STEP_SUMMARY
              echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
              echo "" >> $GITHUB_STEP_SUMMARY
              
              # Add a note if non-Drupal issues also exist
              if [ "$HAS_NON_DRUPAL" = "true" ]; then
                echo "ℹ️ **Note:** The table above includes both Drupal and non-Drupal packages. Non-Drupal vulnerabilities do not affect the Drupal audit result." >> $GITHUB_STEP_SUMMARY
              fi
            elif [ "$HAS_NON_DRUPAL" = "true" ]; then
              echo "✅ **No security vulnerabilities found in Drupal packages!**" >> $GITHUB_STEP_SUMMARY
              echo "" >> $GITHUB_STEP_SUMMARY
              echo "ℹ️ **Security vulnerabilities detected in non-Drupal packages:**" >> $GITHUB_STEP_SUMMARY
              echo "" >> $GITHUB_STEP_SUMMARY
              echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
              tail -n +2 audit_table.txt >> $GITHUB_STEP_SUMMARY
              echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
            fi
            
            # Console output
            if [ "$HAS_DRUPAL" = "true" ]; then
              echo "❌ Drupal security audit failed - vulnerabilities found in Drupal packages"
              echo "Security audit results:"
              tail -n +2 audit_table.txt
              exit 1
            else
              echo "✅ Drupal security audit passed - no vulnerabilities detected in Drupal packages"
              if [ "$HAS_NON_DRUPAL" = "true" ]; then
                echo "ℹ️ Note: Non-Drupal packages have vulnerabilities, but they don't affect Drupal audit status"
              fi
            fi
          else
            echo "✅ **No security vulnerabilities found in any packages!**" >> $GITHUB_STEP_SUMMARY
            echo "✅ Drupal security audit passed - no vulnerabilities detected in any packages"
          fi
