name: PHP CI
on: [push]
jobs:
  php-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - name: Run PHP Tests in src directory
        uses: alleyinteractive/action-test-php@develop
        with:
          php-version: '8.2'
          working-directory: './'
          cache-dependency-path: './composer.lock'
          audit-skip: 'false'
          test-skip: 'true'
          skip-wordpress-install: 'true'
          skip-services: 'true'
          install-skip: 'true'
